### ISSUE TITLE
order of languages specified in conf (e.g.  it,en )  is not kept in the application (en,it)

### ISSUE THREAD

**Issue by pezzacolori** [Insubric/box#100]

**Comment by minettiandrea** [comment]
Tested it and look correct to me, I've also added a test `LanguageOrderTest`.

The logic to chose the language when you load the page the first of the following:
1. If a language is set on the session storage take that one (is set when one changes the language by clicking on the top left link)
2. If the language of the browser existes on the list of the supported messages (defined in box.conf langs) take that one
3. Take the first of the list defined in box.conf langs
4. Fallback to "en"
