### ISSUE TITLE
SHAPEFILE export improvements

### ISSUE THREAD

**Issue by pezzacolori** [Insubric/box#274]
for the export shapefile in table view of a form:
- export shapefiles on fields based on    exportFields and not on tabularFields of the form  
- hide button   export shapefile   if no geometry fields are present in exportFields, otherwise it is confusing since many tables do not have geometries   (eventually evaluate if not using something like Actions   (e.g. downloadActions)

**Comment by minettiandrea** [comment]
Looks like it has been solved
