### ISSUE TITLE
polygon fill is black with microsoft edge

### ISSUE THREAD

**Issue by pezzacolori** [Insubric/box#81]

**Comment by minettiandrea** [comment]
With version Version 85.0.564.51 (Official build) (64-bit) (that uses webkit as engine) works as expected, with wich version you found the issue?

**Comment by pezzacolori** [comment]
It is possible.
Also with Chrome version 53 polygon fill is black (2016) (feedback by cantonal authorities ...).
Also with internet explorer .... which is still used in the administration (aaaargh).

I would not invest too much in this, but maybe there is a quick workaround ...

**Comment by minettiandrea** [comment]
Not got any info on that lately
